//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class userInfoEntities : DbContext
    {
        public userInfoEntities()
            : base("name=userInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<country> countries { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<state> states { get; set; }
        public virtual DbSet<userHobby> userHobbies { get; set; }
        public virtual DbSet<userRole> userRoles { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<userNote> userNotes { get; set; }
        public virtual DbSet<userDocument> userDocuments { get; set; }
    }
}
