//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.userHobbies = new HashSet<userHobby>();
            this.userRoles = new HashSet<userRole>();
            this.userNotes = new HashSet<userNote>();
            this.userDocuments = new HashSet<userDocument>();
        }
    
        public int userId { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string gender { get; set; }
        public System.DateTime dob { get; set; }
        public string profilePic { get; set; }
        public string presentAddressLine1 { get; set; }
        public string presentAddressLine2 { get; set; }
        public int presentCountryId { get; set; }
        public int presentStateId { get; set; }
        public string presentCity { get; set; }
        public string presentPin { get; set; }
        public string permanentAddressLine1 { get; set; }
        public string permanentAddressLine2 { get; set; }
        public int permanentCountryId { get; set; }
        public int permanentStateId { get; set; }
        public string permanentCity { get; set; }
        public string permanentPin { get; set; }
        public string password { get; set; }
    
        public virtual country country { get; set; }
        public virtual country country1 { get; set; }
        public virtual state state { get; set; }
        public virtual state state1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userHobby> userHobbies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userRole> userRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userNote> userNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userDocument> userDocuments { get; set; }
    }
}
