//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageUser.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class userNote
    {
        public int noteId { get; set; }
        public int userId { get; set; }
        public string noteMessage { get; set; }
        public int ifPrivate { get; set; }
        public System.DateTime createdOn { get; set; }
        public string createdBy { get; set; }
    
        public virtual user user { get; set; }
    }
}
